version: '3'

networks:
  bridge:

volumes:
  mysql_db: {}
  logs: {}

services:
  jibasapp:
    image: php56-jibas:latest
    build:
      context: ./images/php
    volumes:
      - "./app:/app"
      - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    networks:
      - bridge
    env_file:
      - .env

  nginx:
    image: nginx:1.21.6
    volumes:
      - "./app:/app"
      - "./etc/nginx:/etc/nginx/conf.d"
    networks:
      - bridge
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:80

  mysql:
    image: mariadb:10.8.2
    volumes:
      - "mysql_db:/var/lib/mysql"
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - bridge
    ports:
      - ${DB_PORT}:3306
